### ISSUE TITLE
Multiple points obtained in one race

### ISSUE THREAD

**Issue by LuizGyro** [DoubleTroubleGames/hooksharks#152]
This probably happens because the one player is invincible (respawning) when another player finishes the race, so they both finish the race

**Comment by arthurtui** [comment]
Still happens, so that's probably not it.

**Comment by rilifon** [comment]
Seems fixed via 0988d3c175587543aa8ffee8c47c73ac56fa4d96. We can re-open the issue if the bug comes up again.
