### ISSUE TITLE
Make an options screen/menu

### ISSUE THREAD

**Issue by ArthurTui** [DoubleTroubleGames/hooksharks#30]
With options like:

- Video
    - Resolution
    - Fullscreen

- Audio
    - Master Volume
    - Music Volume
    - Sound Effects Volume

**Comment by ArthurTui** [comment]
What do you guys think @rilifon @Detril @LuizGyro ?

**Comment by rilifon** [comment]
Cool but shouldn't be our current focus at the moment

Em sex, 8 de fev de 2019 16:36, Arthur <notifications@github.com> escreveu:
